language: python
dist: xenial
python:
  - '3.7'
  - '3.8'
  - '3.9'

before_install:
  - pip install poetry poetry-dynamic-versioning
install:
  - poetry install

script:
  - python -m pytest --cov=anyioc --cov-report=term --cov-report=html

jobs:
  include:
    - stage: deploy
      python: 3.9
      script:
        - poetry build
      deploy:
        provider: script
        script: poetry publish -u __token__ -p $PYPI_TOKEN
        skip_cleanup: true
        on:
          tags: true
